### ISSUE TITLE
Not Symmetrical power Calculation plot 

### ISSUE THREAD

**Issue by RoaaNaa** [kn3in/mRnd#2]
Hello 
I tried to calculate the power for  schizophrenia data with those value :
N =55.374
R2xz =0.028
K =0.36
alpha=0.05
and OR =[0:2]
and the plot that i had not symmetrical!! 
Please help me ...
[powerestimatinpropRplot.pdf](https://github.com/kn3in/mRnd/files/3296569/powerestimatinpropRplot.pdf)

**Comment by kn3in** [comment]
Hi @RoaaNaa,
Odds ratio is not symmetric around one, the logarithm of it is. For example, increasing value by two and decreasing it by two will give ratios 2 and 0.5 respectively, which are not symmetric around 1. On the other hand log2(2) = 1 and log2(0.5) = -1 (and log2(1) = 0). This is to say if you take a log of your x values the plot will be symmetric.
Cheers,
Kostya
