### ISSUE TITLE
Is the web tool mRnd suitable for binary exposures?

### ISSUE THREAD

**Issue by Hellenzz** [kn3in/mRnd#3]
Hi,

Is the online web tool (https://shiny.cnsgenomics.com/mRnd/) suitable for MR analysis using binary traits such as hypertension as the exposure? 

Best,
Hellen

**Comment by kn3in** [comment]
Hi Hellen,
Yes, there is a binary outcome tab. You might try this branch https://github.com/kn3in/mRnd/tree/binary-fix or use Stephen Burgess  power calculator https://sb452.shinyapps.io/power/  for the situations when disease prevalence is low (i.e. population study as opposed to case-control setup).
Cheers,
Kostya

**Comment by Hellenzz** [comment]
Hi Kostya,
Yes, both the branch and Stephen Burgess power calculator can be used for binary outcomes, but I want to calculate power for MR with a binary exposure and a continuous outcome. If the continuous outcome tab can do this, should the σ2(x) (e.g., variance of the binary exposure variable X) be calculated as p*(1-p) where p means the prevalence of the binary exposure?
Thanks,
Hellen

**Comment by kn3in** [comment]
Sorry, Hellen. I was too quick to answer, didn't read your question properly. Yes, I would use the variance of a binary exposure as the variance of X.

**Comment by Hellenzz** [comment]
Thank you very much for the information, Kostya.

**Comment by kn3in** [comment]
Hi Hellen,
Please read a blog post by Stephen Burgess @sb452 which addresses your question:  http://www.mendelianrandomization.com/index.php/blog/67-power-in-mendelian-randomization-with-a-binary-exposure
Cheers,
Kostya

**Comment by Hellenzz** [comment]
Hi Kostya,
The blog is helpful. Many thanks again for the great support!
Cheers, 
Hellen
